version: '3'

services:
  php-fpm:
    build:
        context: ./php-fpm
  nginx:
    build:
        context: ./nginx
    volumes:
        - ../src:/var/www/src
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
        - ./nginx/sites/:/etc/nginx/sites-available/
        - ./nginx/conf.d/:/etc/nginx/conf.d/
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
    depends_on:
        - php-fpm
    ports:
        - "80:80"
        - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  database:
    build:
        context: ./database
    environment:
        - MYSQL_DATABASE=mydb
        - MYSQL_USER=myuser
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=docker
    volumes:
        - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql
