version: "3"

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../src:/var/www/src
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm
  database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=eventano
      - MYSQL_USER=event
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
      - TZ=Europe/Berlin
    volumes:
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql
